# Generated by Django 6.0.3 on 2026-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_sysconfig", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configvalue",
            name="path",
            field=models.CharField(
                help_text="Configuration path, e.g., 'general.max_todos_per_user'",
                max_length=255,
            ),
        ),
    ]
